In [13]:
from sklearn.ensemble import RandomForestClassifier
from modules.benchmark import quick_load, xy_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from xgboost import XGBClassifier
import dalex as dx

In [3]:
visco = quick_load(feature='expert_chen', columns=['smiles_surfactant1', 'smiles_surfactant2', 'smiles_additive1', 'smiles_additive2'])

## Random forest

In [6]:
X, y, groups = xy_split(visco)

categorical_features = ['type_surfactant1', 'type_surfactant2']
numerical_features = []

for column in X.columns:
    if X[column].dtype in ('float64', 'int64'):
        numerical_features.append(column)

preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_features),
        ('cat', OneHotEncoder(), categorical_features)
    ]
)

classifier = RandomForestClassifier(
    random_state=42,
    n_estimators=100,
    min_samples_leaf=5,
    min_samples_split=10
)

model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", classifier)
])

model.fit(X, y)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', 'passthrough',
                                                  ['c_surfactant1',
                                                   'c_surfactant2',
                                                   'c_additive1', 'c_additive2',
                                                   'temperature',
                                                   'surfactant1_chen_MolLogP',
                                                   'surfactant1_chen_Chi1v',
                                                   'surfactant1_chen_VSA_EState7',
                                                   'surfactant1_chen_VSA_EState8',
                                                   'surfactant1_chen_qed',
                                                   'surfactant1_chen_FpDensityMorgan1',
                                                   'surfactant1_chen...
                                                   'surfactant1_chen_PEOE_VSA8',
                                                   'surfactant1_molecular_weight',
                                                   'surfactant1_tail_length',
                                                   'surfactant2_chen_MolLogP',
                                                   'surfactant2_chen_Chi1v',
                                                   'surfactant2_chen_VSA_EState7',
                                                   'surfactant2_chen_VSA_EState8', ...]),
                                                 ('cat', OneHotEncoder(),
                                                  ['type_surfactant1',
                                                   'type_surfactant2'])])),
                ('classifier',
                 RandomForestClassifier(min_samples_leaf=5,
                                        min_samples_split=10,
                                        random_state=42))])

In [8]:
explainer = dx.Explainer(
    model,
    X,
    y,
    label="Random Forest"
)

Preparation of a new explainer is initiated

  -> data              : 8152 rows 91 cols
  -> target variable   : Parameter 'y' was a pandas.Series. Converted to a numpy.ndarray.
  -> target variable   : 8152 values
  -> model_class       : sklearn.ensemble._forest.RandomForestClassifier (default)
  -> label             : Random Forest
  -> predict function  : <function yhat_proba_default at 0x000002B4EF1F4A40> will be used (default)
  -> predict function  : Accepts only pandas.DataFrame, numpy.ndarray causes problems.
  -> predicted values  : min = 0.0, mean = 0.716, max = 1.0
  -> model type        : classification will be used (default)
  -> residual function : difference between y and yhat (default)
  -> residuals         : min = -0.933, mean = -0.000686, max = 0.8
  -> model_info        : package sklearn

A new explainer has been created!

In [10]:
importance = explainer.model_parts(loss_function="1-auc")

In [11]:
importance.plot()

## XGBoost - expert chen

In [14]:
classifier = XGBClassifier(
        n_estimators=300,
        max_depth=5,
        learning_rate=0.05,
        objective="binary:logistic",
        eval_metric="logloss",
        random_state=42
)

model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", classifier)
])

model.fit(X, y)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', 'passthrough',
                                                  ['c_surfactant1',
                                                   'c_surfactant2',
                                                   'c_additive1', 'c_additive2',
                                                   'temperature',
                                                   'surfactant1_chen_MolLogP',
                                                   'surfactant1_chen_Chi1v',
                                                   'surfactant1_chen_VSA_EState7',
                                                   'surfactant1_chen_VSA_EState8',
                                                   'surfactant1_chen_qed',
                                                   'surfactant1_chen_FpDensityMorgan1',
                                                   'surfactant1_chen...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=5, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [18]:
explainer = dx.Explainer(
    model,
    X,
    y,
    label="XGBoost"
)

Preparation of a new explainer is initiated

  -> data              : 8152 rows 91 cols
  -> target variable   : Parameter 'y' was a pandas.Series. Converted to a numpy.ndarray.
  -> target variable   : 8152 values
  -> model_class       : xgboost.sklearn.XGBClassifier (default)
  -> label             : XGBoost
  -> predict function  : <function yhat_proba_default at 0x000002B4EF1F4A40> will be used (default)
  -> predict function  : Accepts only pandas.DataFrame, numpy.ndarray causes problems.
  -> predicted values  : min = 0.0011, mean = 0.716, max = 0.999
  -> model type        : classification will be used (default)
  -> residual function : difference between y and yhat (default)
  -> residuals         : min = -0.985, mean = -9.93e-05, max = 0.871
  -> model_info        : package sklearn

A new explainer has been created!

In [19]:
importance = explainer.model_parts(loss_function="1-auc")

In [20]:
importance.plot()

In [23]:
importance.result[-15:]

                              variable  dropout_loss    label
78                surfactant1_chen_qed      0.005269  XGBoost
79  surfactant1_chen_MaxAbsEStateIndex      0.005360  XGBoost
80        additive1_chen_HallKierAlpha      0.005510  XGBoost
81            surfactant2_chen_MolLogP      0.005692  XGBoost
82                surfactant2_chen_qed      0.005931  XGBoost
83                         c_additive2      0.006063  XGBoost
84          additive1_molecular_weight      0.006275  XGBoost
85                additive1_chen_Chi1v      0.006358  XGBoost
86   surfactant2_chen_FpDensityMorgan1      0.008834  XGBoost
87          surfactant1_chen_PEOE_VSA6      0.015244  XGBoost
88                       c_surfactant2      0.030136  XGBoost
89                         c_additive1      0.041000  XGBoost
90                       c_surfactant1      0.041050  XGBoost
91                         temperature      0.053429  XGBoost
92                          _baseline_      0.496728  XGBoost

# XGBoost - bcut2d

In [29]:
visco = quick_load(feature='bcut2d', columns=['smiles_surfactant1', 'smiles_surfactant2', 'smiles_additive1', 'smiles_additive2'])

In [30]:
X, y, groups = xy_split(visco)

categorical_features = ['type_surfactant1', 'type_surfactant2']
numerical_features = []

for column in X.columns:
    if X[column].dtype in ('float64', 'int64'):
        numerical_features.append(column)

preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_features),
        ('cat', OneHotEncoder(), categorical_features)
    ]
)

classifier = XGBClassifier(
        n_estimators=300,
        max_depth=5,
        learning_rate=0.05,
        objective="binary:logistic",
        eval_metric="logloss",
        random_state=42
)

model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", classifier)
])

model.fit(X, y)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', 'passthrough',
                                                  ['c_surfactant1',
                                                   'c_surfactant2',
                                                   'c_additive1', 'c_additive2',
                                                   'temperature',
                                                   'surfactant1_burden_eigenvalue_mass_max',
                                                   'surfactant1_burden_eigenvalue_mass_min',
                                                   'surfactant1_burden_eigenvalue_charge_max',
                                                   'surfactant1_burden_eigenvalue_charge_min',
                                                   'surfactant1_burden_ei...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=5, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [34]:
explainer = dx.Explainer(model, X, y, label="XGBoost")

Preparation of a new explainer is initiated

  -> data              : 8152 rows 39 cols
  -> target variable   : Parameter 'y' was a pandas.Series. Converted to a numpy.ndarray.
  -> target variable   : 8152 values
  -> model_class       : xgboost.sklearn.XGBClassifier (default)
  -> label             : XGBoost
  -> predict function  : <function yhat_proba_default at 0x000002B4EF1F4A40> will be used (default)
  -> predict function  : Accepts only pandas.DataFrame, numpy.ndarray causes problems.
  -> predicted values  : min = 0.000838, mean = 0.716, max = 1.0
  -> model type        : classification will be used (default)
  -> residual function : difference between y and yhat (default)
  -> residuals         : min = -0.987, mean = -0.000108, max = 0.932
  -> model_info        : package sklearn

A new explainer has been created!

In [35]:
importance = explainer.model_parts(loss_function="1-auc")

In [36]:
importance.plot()

In [37]:
importance.result[-15:]

                                  variable  dropout_loss    label
26    additive1_burden_eigenvalue_mass_min      0.006033  XGBoost
27  surfactant2_burden_eigenvalue_logp_min      0.006137  XGBoost
28    additive1_burden_eigenvalue_mass_max      0.006187  XGBoost
29      additive1_burden_eigenvalue_mr_max      0.006204  XGBoost
30    additive1_burden_eigenvalue_logp_max      0.006366  XGBoost
31    surfactant1_burden_eigenvalue_mr_min      0.006878  XGBoost
32      additive1_burden_eigenvalue_mr_min      0.006986  XGBoost
33  surfactant1_burden_eigenvalue_logp_min      0.007168  XGBoost
34    surfactant1_burden_eigenvalue_mr_max      0.008144  XGBoost
35  surfactant1_burden_eigenvalue_mass_min      0.011058  XGBoost
36                           c_surfactant2      0.032221  XGBoost
37                           c_surfactant1      0.044732  XGBoost
38                             temperature      0.048141  XGBoost
39                             c_additive1      0.060550  XGBoost
40                              _baseline_      0.499255  XGBoost

# XGBoost - Avalon

In [38]:
visco = quick_load(feature='avalon', columns=['smiles_surfactant1', 'smiles_surfactant2', 'smiles_additive1', 'smiles_additive2'])

In [39]:
X, y, groups = xy_split(visco)

categorical_features = ['type_surfactant1', 'type_surfactant2']
numerical_features = []

for column in X.columns:
    if X[column].dtype in ('float64', 'int64'):
        numerical_features.append(column)

preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_features),
        ('cat', OneHotEncoder(), categorical_features)
    ]
)

classifier = XGBClassifier(
        n_estimators=300,
        max_depth=5,
        learning_rate=0.05,
        objective="binary:logistic",
        eval_metric="logloss",
        random_state=42
)

model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", classifier)
])

model.fit(X, y)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', 'passthrough',
                                                  ['c_surfactant1',
                                                   'c_surfactant2',
                                                   'c_additive1', 'c_additive2',
                                                   'temperature',
                                                   'surfactant1_avalon_0',
                                                   'surfactant1_avalon_1',
                                                   'surfactant1_avalon_2',
                                                   'surfactant1_avalon_3',
                                                   'surfactant1_avalon_4',
                                                   'surfactant1_avalon_5',
                                                   'surfactant1_avalon_6',
                                                   'surfactant1_avalon_7',
                                                   'surfa...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=5, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [40]:
explainer = dx.Explainer(model, X, y, label="XGBoost")

Preparation of a new explainer is initiated

  -> data              : 8152 rows 1031 cols
  -> target variable   : Parameter 'y' was a pandas.Series. Converted to a numpy.ndarray.
  -> target variable   : 8152 values
  -> model_class       : xgboost.sklearn.XGBClassifier (default)
  -> label             : XGBoost
  -> predict function  : <function yhat_proba_default at 0x000002B4EF1F4A40> will be used (default)
  -> predict function  : Accepts only pandas.DataFrame, numpy.ndarray causes problems.
  -> predicted values  : min = 0.00304, mean = 0.715, max = 1.0
  -> model type        : classification will be used (default)
  -> residual function : difference between y and yhat (default)
  -> residuals         : min = -0.979, mean = 2.93e-06, max = 0.853
  -> model_info        : package sklearn

A new explainer has been created!

In [41]:
importance = explainer.model_parts(loss_function="1-auc")

In [42]:
importance.plot()

In [43]:
importance.result[-15:]

                    variable  dropout_loss    label
1018   surfactant1_avalon_49      0.005856  XGBoost
1019   surfactant1_avalon_25      0.005885  XGBoost
1020    additive1_avalon_110      0.005894  XGBoost
1021    additive1_avalon_199      0.006007  XGBoost
1022  surfactant1_avalon_110      0.006034  XGBoost
1023   surfactant1_avalon_79      0.006146  XGBoost
1024             c_additive2      0.006700  XGBoost
1025        type_surfactant1      0.007593  XGBoost
1026    additive1_avalon_251      0.008151  XGBoost
1027   surfactant2_avalon_23      0.008661  XGBoost
1028           c_surfactant2      0.031788  XGBoost
1029           c_surfactant1      0.050860  XGBoost
1030             c_additive1      0.058232  XGBoost
1031             temperature      0.076501  XGBoost
1032              _baseline_      0.504005  XGBoost

# XGBoost - MACCS

In [44]:
visco = quick_load(feature='maccs', columns=['smiles_surfactant1', 'smiles_surfactant2', 'smiles_additive1', 'smiles_additive2'])

In [45]:
X, y, groups = xy_split(visco)

categorical_features = ['type_surfactant1', 'type_surfactant2']
numerical_features = []

for column in X.columns:
    if X[column].dtype in ('float64', 'int64'):
        numerical_features.append(column)

preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_features),
        ('cat', OneHotEncoder(), categorical_features)
    ]
)

classifier = XGBClassifier(
        n_estimators=300,
        max_depth=5,
        learning_rate=0.05,
        objective="binary:logistic",
        eval_metric="logloss",
        random_state=42
)

model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", classifier)
])

model.fit(X, y)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', 'passthrough',
                                                  ['c_surfactant1',
                                                   'c_surfactant2',
                                                   'c_additive1', 'c_additive2',
                                                   'temperature',
                                                   'surfactant1_maccs_1',
                                                   'surfactant1_maccs_2',
                                                   'surfactant1_maccs_3',
                                                   'surfactant1_maccs_4',
                                                   'surfactant1_maccs_5',
                                                   'surfactant1_maccs_6',
                                                   'surfactant1_maccs_7',
                                                   'surfactant1_maccs_8',
                                                   'surfactant1_m...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=5, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [46]:
explainer = dx.Explainer(model, X, y, label="XGBoost")

Preparation of a new explainer is initiated

  -> data              : 8152 rows 671 cols
  -> target variable   : Parameter 'y' was a pandas.Series. Converted to a numpy.ndarray.
  -> target variable   : 8152 values
  -> model_class       : xgboost.sklearn.XGBClassifier (default)
  -> label             : XGBoost
  -> predict function  : <function yhat_proba_default at 0x000002B4EF1F4A40> will be used (default)
  -> predict function  : Accepts only pandas.DataFrame, numpy.ndarray causes problems.
  -> predicted values  : min = 0.00144, mean = 0.715, max = 1.0
  -> model type        : classification will be used (default)
  -> residual function : difference between y and yhat (default)
  -> residuals         : min = -0.975, mean = 2.26e-05, max = 0.877
  -> model_info        : package sklearn

A new explainer has been created!

In [47]:
importance = explainer.model_parts(loss_function="1-auc")

In [48]:
importance.plot()

In [49]:
importance.result[-15:]

                  variable  dropout_loss    label
658    additive1_maccs_102      0.006304  XGBoost
659  surfactant1_maccs_162      0.006364  XGBoost
660    additive1_maccs_162      0.006415  XGBoost
661    additive2_maccs_103      0.006457  XGBoost
662   surfactant1_maccs_99      0.006640  XGBoost
663  surfactant1_maccs_139      0.006752  XGBoost
664    additive1_maccs_146      0.006794  XGBoost
665            c_additive2      0.007318  XGBoost
666   surfactant2_maccs_72      0.008116  XGBoost
667       type_surfactant1      0.010065  XGBoost
668          c_surfactant2      0.031018  XGBoost
669          c_surfactant1      0.047783  XGBoost
670            c_additive1      0.050094  XGBoost
671            temperature      0.079364  XGBoost
672             _baseline_      0.488254  XGBoost

# XGBoost - physiochemical

In [54]:
visco = quick_load(feature='physiochemical', columns=['smiles_surfactant1', 'smiles_surfactant2', 'smiles_additive1', 'smiles_additive2'])

In [55]:
X, y, groups = xy_split(visco)

categorical_features = ['type_surfactant1', 'type_surfactant2']
numerical_features = []

for column in X.columns:
    if X[column].dtype in ('float64', 'int64'):
        numerical_features.append(column)

preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_features),
        ('cat', OneHotEncoder(), categorical_features)
    ]
)

classifier = XGBClassifier(
        n_estimators=300,
        max_depth=5,
        learning_rate=0.05,
        objective="binary:logistic",
        eval_metric="logloss",
        random_state=42
)

model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", classifier)
])

model.fit(X, y)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', 'passthrough',
                                                  ['c_surfactant1',
                                                   'c_surfactant2',
                                                   'c_additive1', 'c_additive2',
                                                   'temperature',
                                                   'surfactant1_fp_0',
                                                   'surfactant1_fp_1',
                                                   'surfactant1_fp_2',
                                                   'surfactant1_fp_3',
                                                   'surfactant1_fp_4',
                                                   'surfactant1_fp_5',
                                                   'surfactant1_fp_6',
                                                   'surfactant1_fp_7',
                                                   'surfactant1_fp_8',
                                                   'surfactant1_fp_9',...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=5, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [56]:
explainer = dx.Explainer(model, X, y, label="XGBoost")

Preparation of a new explainer is initiated

  -> data              : 8152 rows 1031 cols
  -> target variable   : Parameter 'y' was a pandas.Series. Converted to a numpy.ndarray.
  -> target variable   : 8152 values
  -> model_class       : xgboost.sklearn.XGBClassifier (default)
  -> label             : XGBoost
  -> predict function  : <function yhat_proba_default at 0x000002B4EF1F4A40> will be used (default)
  -> predict function  : Accepts only pandas.DataFrame, numpy.ndarray causes problems.
  -> predicted values  : min = 0.0021, mean = 0.715, max = 1.0
  -> model type        : classification will be used (default)
  -> residual function : difference between y and yhat (default)
  -> residuals         : min = -0.975, mean = -6.89e-05, max = 0.919
  -> model_info        : package sklearn

A new explainer has been created!

In [57]:
importance = explainer.model_parts(loss_function="1-auc")

In [58]:
importance.plot()

In [59]:
importance.result[-15:]

                variable  dropout_loss    label
1018  surfactant2_fp_225      0.006329  XGBoost
1019    additive1_fp_165      0.006389  XGBoost
1020         c_additive2      0.006928  XGBoost
1021  surfactant1_fp_225      0.006962  XGBoost
1022   surfactant1_fp_97      0.006964  XGBoost
1023   surfactant1_fp_67      0.007416  XGBoost
1024   surfactant1_fp_47      0.008536  XGBoost
1025     additive1_fp_65      0.008901  XGBoost
1026   surfactant1_fp_45      0.009336  XGBoost
1027  surfactant2_fp_112      0.011474  XGBoost
1028       c_surfactant2      0.030369  XGBoost
1029         c_additive1      0.038886  XGBoost
1030       c_surfactant1      0.061715  XGBoost
1031         temperature      0.083991  XGBoost
1032          _baseline_      0.493281  XGBoost